# Generated by Django 4.1.3 on 2023-10-18 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('process', 'Process'), ('shipping', 'Shipping'), ('cancel', 'Cancel')], default='process', max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.IntegerField()),
                ('payment_option', models.CharField(choices=[('cash', 'CASH ON PRICE'), ('upi', 'UPI SYSTEM')], default='cash', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
